"""orders, order lines, returns

Revision ID: 3fa6431fc8b8
Revises: 1e5f12b7b75b
Create Date: 2026-07-22 08:36:07.444165

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fa6431fc8b8"
down_revision: str | None = "1e5f12b7b75b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_statuses")),
        sa.UniqueConstraint("code", name=op.f("uq_order_statuses_code")),
    )
    op.create_index(
        op.f("ix_order_statuses_updated_at"), "order_statuses", ["updated_at"], unique=False
    )
    op.create_table(
        "return_dispositions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_return_dispositions")),
        sa.UniqueConstraint("code", name=op.f("uq_return_dispositions_code")),
    )
    op.create_index(
        op.f("ix_return_dispositions_updated_at"),
        "return_dispositions",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "return_reasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_return_reasons")),
        sa.UniqueConstraint("code", name=op.f("uq_return_reasons_code")),
    )
    op.create_index(
        op.f("ix_return_reasons_updated_at"), "return_reasons", ["updated_at"], unique=False
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("address_line1", sa.String(length=200), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state_province", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_id"], ["regions.id"], name=op.f("fk_customers_region_id_regions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("customer_code", name=op.f("uq_customers_customer_code")),
    )
    op.create_index(op.f("ix_customers_updated_at"), "customers", ["updated_at"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_number", sa.String(length=30), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_orders_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["status_id"], ["order_statuses.id"], name=op.f("fk_orders_status_id_order_statuses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("order_number", name=op.f("uq_orders_order_number")),
    )
    op.create_index(op.f("ix_orders_updated_at"), "orders", ["updated_at"], unique=False)
    op.create_table(
        "order_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("ordered_quantity", sa.Integer(), nullable=False),
        sa.Column("allocated_quantity", sa.Integer(), nullable=False),
        sa.Column("backordered_quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("fulfillment_warehouse_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "allocated_quantity + backordered_quantity <= ordered_quantity",
            name=op.f("ck_order_lines_allocated_plus_backordered_within_ordered"),
        ),
        sa.CheckConstraint(
            "allocated_quantity >= 0", name=op.f("ck_order_lines_allocated_quantity_non_negative")
        ),
        sa.CheckConstraint(
            "backordered_quantity >= 0",
            name=op.f("ck_order_lines_backordered_quantity_non_negative"),
        ),
        sa.CheckConstraint(
            "ordered_quantity > 0", name=op.f("ck_order_lines_ordered_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["fulfillment_warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_order_lines_fulfillment_warehouse_id_warehouses"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_lines_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_order_lines_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_lines")),
        sa.UniqueConstraint(
            "order_id", "line_number", name=op.f("uq_order_lines_order_id_line_number")
        ),
    )
    op.create_index(op.f("ix_order_lines_updated_at"), "order_lines", ["updated_at"], unique=False)
    op.create_table(
        "returns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("return_number", sa.String(length=30), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("return_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_returns_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_returns")),
        sa.UniqueConstraint("return_number", name=op.f("uq_returns_return_number")),
    )
    op.create_index(op.f("ix_returns_updated_at"), "returns", ["updated_at"], unique=False)
    op.create_table(
        "return_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("return_id", sa.Integer(), nullable=False),
        sa.Column("order_line_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("returned_quantity", sa.Integer(), nullable=False),
        sa.Column("reason_id", sa.Integer(), nullable=False),
        sa.Column("disposition_id", sa.Integer(), nullable=True),
        sa.Column("inspected_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "returned_quantity > 0", name=op.f("ck_return_lines_returned_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["disposition_id"],
            ["return_dispositions.id"],
            name=op.f("fk_return_lines_disposition_id_return_dispositions"),
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_return_lines_order_line_id_order_lines"),
        ),
        sa.ForeignKeyConstraint(
            ["reason_id"],
            ["return_reasons.id"],
            name=op.f("fk_return_lines_reason_id_return_reasons"),
        ),
        sa.ForeignKeyConstraint(
            ["return_id"], ["returns.id"], name=op.f("fk_return_lines_return_id_returns")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_return_lines")),
        sa.UniqueConstraint(
            "return_id", "line_number", name=op.f("uq_return_lines_return_id_line_number")
        ),
    )
    op.create_index(
        op.f("ix_return_lines_updated_at"), "return_lines", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_return_lines_updated_at"), table_name="return_lines")
    op.drop_table("return_lines")
    op.drop_index(op.f("ix_returns_updated_at"), table_name="returns")
    op.drop_table("returns")
    op.drop_index(op.f("ix_order_lines_updated_at"), table_name="order_lines")
    op.drop_table("order_lines")
    op.drop_index(op.f("ix_orders_updated_at"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_customers_updated_at"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_return_reasons_updated_at"), table_name="return_reasons")
    op.drop_table("return_reasons")
    op.drop_index(op.f("ix_return_dispositions_updated_at"), table_name="return_dispositions")
    op.drop_table("return_dispositions")
    op.drop_index(op.f("ix_order_statuses_updated_at"), table_name="order_statuses")
    op.drop_table("order_statuses")
    # ### end Alembic commands ###
