"""inventory positions + transactions

Revision ID: 8e223e3f6d73
Revises: 3518b4c8151c
Create Date: 2026-07-22 08:29:01.100186

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e223e3f6d73"
down_revision: str | None = "3518b4c8151c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_transaction_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_transaction_types")),
        sa.UniqueConstraint("code", name=op.f("uq_inventory_transaction_types_code")),
    )
    op.create_index(
        op.f("ix_inventory_transaction_types_updated_at"),
        "inventory_transaction_types",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "inventory_positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_zone_id", sa.Integer(), nullable=False),
        sa.Column("quantity_on_hand", sa.Integer(), nullable=False),
        sa.Column("quantity_reserved", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "quantity_on_hand >= 0",
            name=op.f("ck_inventory_positions_quantity_on_hand_non_negative"),
        ),
        sa.CheckConstraint(
            "quantity_reserved >= 0",
            name=op.f("ck_inventory_positions_quantity_reserved_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_inventory_positions_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_positions_warehouse_id_warehouses"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_zone_id"],
            ["warehouse_zones.id"],
            name=op.f("fk_inventory_positions_warehouse_zone_id_warehouse_zones"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_positions")),
        sa.UniqueConstraint(
            "product_id",
            "warehouse_id",
            "warehouse_zone_id",
            name=op.f("uq_inventory_positions_product_id_warehouse_id_warehouse_zone_id"),
        ),
    )
    op.create_index(
        op.f("ix_inventory_positions_updated_at"),
        "inventory_positions",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "inventory_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("inventory_position_id", sa.Integer(), nullable=False),
        sa.Column("transaction_type_id", sa.Integer(), nullable=False),
        sa.Column("quantity_delta", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("source_reference_type", sa.String(length=30), nullable=True),
        sa.Column("source_reference_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_position_id"],
            ["inventory_positions.id"],
            name=op.f("fk_inventory_transactions_inventory_position_id_inventory_positions"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_type_id"],
            ["inventory_transaction_types.id"],
            name=op.f("fk_inventory_transactions_transaction_type_id_inventory_transaction_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_transactions")),
    )
    op.create_index(
        op.f("ix_inventory_transactions_occurred_at"),
        "inventory_transactions",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_transactions_updated_at"),
        "inventory_transactions",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inventory_transactions_updated_at"), table_name="inventory_transactions")
    op.drop_index(
        op.f("ix_inventory_transactions_occurred_at"), table_name="inventory_transactions"
    )
    op.drop_table("inventory_transactions")
    op.drop_index(op.f("ix_inventory_positions_updated_at"), table_name="inventory_positions")
    op.drop_table("inventory_positions")
    op.drop_index(
        op.f("ix_inventory_transaction_types_updated_at"), table_name="inventory_transaction_types"
    )
    op.drop_table("inventory_transaction_types")
    # ### end Alembic commands ###
