"""transportation: carriers, shipments, events

Revision ID: cd15da4c273a
Revises: 3fa6431fc8b8
Create Date: 2026-07-22 08:49:05.179058

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd15da4c273a"
down_revision: str | None = "3fa6431fc8b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipment_statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_statuses")),
        sa.UniqueConstraint("code", name=op.f("uq_shipment_statuses_code")),
    )
    op.create_index(
        op.f("ix_shipment_statuses_updated_at"), "shipment_statuses", ["updated_at"], unique=False
    )
    op.create_table(
        "vehicle_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("capacity_units", sa.Integer(), nullable=False),
        sa.Column("cost_per_mile", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_types")),
        sa.UniqueConstraint("code", name=op.f("uq_vehicle_types_code")),
    )
    op.create_index(
        op.f("ix_vehicle_types_updated_at"), "vehicle_types", ["updated_at"], unique=False
    )
    op.create_table(
        "carriers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("carrier_code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("vehicle_type_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["vehicle_type_id"],
            ["vehicle_types.id"],
            name=op.f("fk_carriers_vehicle_type_id_vehicle_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carriers")),
        sa.UniqueConstraint("carrier_code", name=op.f("uq_carriers_carrier_code")),
    )
    op.create_index(op.f("ix_carriers_updated_at"), "carriers", ["updated_at"], unique=False)
    op.create_table(
        "shipments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shipment_number", sa.String(length=30), nullable=False),
        sa.Column("carrier_id", sa.Integer(), nullable=False),
        sa.Column("origin_warehouse_id", sa.Integer(), nullable=False),
        sa.Column("destination_warehouse_id", sa.Integer(), nullable=True),
        sa.Column("destination_customer_id", sa.Integer(), nullable=True),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("ship_date", sa.Date(), nullable=True),
        sa.Column("estimated_delivery_date", sa.Date(), nullable=True),
        sa.Column("actual_delivery_date", sa.Date(), nullable=True),
        sa.Column("distance_miles", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("shipping_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(destination_warehouse_id IS NOT NULL AND destination_customer_id IS NULL) OR (destination_warehouse_id IS NULL AND destination_customer_id IS NOT NULL)",
            name=op.f("ck_shipments_exactly_one_destination"),
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"], ["carriers.id"], name=op.f("fk_shipments_carrier_id_carriers")
        ),
        sa.ForeignKeyConstraint(
            ["destination_customer_id"],
            ["customers.id"],
            name=op.f("fk_shipments_destination_customer_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["destination_warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_shipments_destination_warehouse_id_warehouses"),
        ),
        sa.ForeignKeyConstraint(
            ["origin_warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_shipments_origin_warehouse_id_warehouses"),
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["shipment_statuses.id"],
            name=op.f("fk_shipments_status_id_shipment_statuses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
        sa.UniqueConstraint("shipment_number", name=op.f("uq_shipments_shipment_number")),
    )
    op.create_index(op.f("ix_shipments_updated_at"), "shipments", ["updated_at"], unique=False)
    op.create_table(
        "shipment_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shipment_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"], ["shipments.id"], name=op.f("fk_shipment_events_shipment_id_shipments")
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["shipment_statuses.id"],
            name=op.f("fk_shipment_events_status_id_shipment_statuses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_events")),
    )
    op.create_index(
        op.f("ix_shipment_events_updated_at"), "shipment_events", ["updated_at"], unique=False
    )
    op.add_column("order_lines", sa.Column("shipment_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_order_lines_shipment_id_shipments"),
        "order_lines",
        "shipments",
        ["shipment_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_order_lines_shipment_id_shipments"), "order_lines", type_="foreignkey"
    )
    op.drop_column("order_lines", "shipment_id")
    op.drop_index(op.f("ix_shipment_events_updated_at"), table_name="shipment_events")
    op.drop_table("shipment_events")
    op.drop_index(op.f("ix_shipments_updated_at"), table_name="shipments")
    op.drop_table("shipments")
    op.drop_index(op.f("ix_carriers_updated_at"), table_name="carriers")
    op.drop_table("carriers")
    op.drop_index(op.f("ix_vehicle_types_updated_at"), table_name="vehicle_types")
    op.drop_table("vehicle_types")
    op.drop_index(op.f("ix_shipment_statuses_updated_at"), table_name="shipment_statuses")
    op.drop_table("shipment_statuses")
    # ### end Alembic commands ###
